---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check kibana version
  - name: Example assertion
    assert:
      that: true

