---
    - name: Upload tar.gz Elasticsearch from local storage
      copy:
        src: "{{ elastic_doun }}"
        dest: "/tmp/elasticsearch-{{ elastic_version }}.tar.gz"
        mode: 0755
      register: Upload_elastic
      until: Upload_elastic is succeeded
      tags: elastic
    - name: Create directrory for Elasticsearch
      file:
        state: directory
        path: "{{ elastic_home }}"
      tags: elastic
    - name: Extract Elasticsearch in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/elasticsearch-{{ elastic_version }}.tar.gz/elasticsearch-7.10.1-linux-x86_64.tar.gz"
        dest: "{{ elastic_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ elastic_home }}/bin/elasticsearch"
      tags:
        - elastic
    - name: Set environment Elastic
      become: true
      template:
        src: templates/elk.sh.j2
        dest: /etc/profile.d/elk.sh
      tags: elastic
